-- Optional sample catalogue. Samples start archived: review details and replace reference imagery before activating in admin.
insert into public.products (id,name,slug,description,fabric,color,price,discount_price,stock,category,collection,images,is_featured,is_active) values ('00000000-0000-4000-8000-000000000001','Gulab Banarasi Silk','gulab-banarasi-silk','An elegant drape with delicate zari-inspired detailing and a beautifully finished border. A timeless addition to your occasion wardrobe. Includes an unstitched blouse piece. Dry clean recommended.','Silk','Wine',8990,null,5,'Banarasi','Wedding Edit','[{"url":"reference:0","alt":"Wine Silk saree"}]',true,false) on conflict (slug) do nothing;
insert into public.products (id,name,slug,description,fabric,color,price,discount_price,stock,category,collection,images,is_featured,is_active) values ('00000000-0000-4000-8000-000000000002','Noor Tissue Silk','noor-tissue-silk','An elegant drape with delicate zari-inspired detailing and a beautifully finished border. A timeless addition to your occasion wardrobe. Includes an unstitched blouse piece. Dry clean recommended.','Tissue silk','Champagne',6490,null,6,'Tissue','Banarasi Heirlooms','[{"url":"reference:1","alt":"Champagne Tissue silk saree"}]',true,false) on conflict (slug) do nothing;
insert into public.products (id,name,slug,description,fabric,color,price,discount_price,stock,category,collection,images,is_featured,is_active) values ('00000000-0000-4000-8000-000000000003','Ragini Zari Saree','ragini-zari-saree','An elegant drape with delicate zari-inspired detailing and a beautifully finished border. A timeless addition to your occasion wardrobe. Includes an unstitched blouse piece. Dry clean recommended.','Silk','Ruby',7290,null,7,'Banarasi','Festive Reverie','[{"url":"reference:2","alt":"Ruby Silk saree"}]',true,false) on conflict (slug) do nothing;
insert into public.products (id,name,slug,description,fabric,color,price,discount_price,stock,category,collection,images,is_featured,is_active) values ('00000000-0000-4000-8000-000000000004','Sunehri Chanderi','sunehri-chanderi','An elegant drape with delicate zari-inspired detailing and a beautifully finished border. A timeless addition to your occasion wardrobe. Includes an unstitched blouse piece. Dry clean recommended.','Chanderi','Gold',4290,null,8,'Chanderi','Everyday Elegance','[{"url":"reference:3","alt":"Gold Chanderi saree"}]',true,false) on conflict (slug) do nothing;
insert into public.products (id,name,slug,description,fabric,color,price,discount_price,stock,category,collection,images,is_featured,is_active) values ('00000000-0000-4000-8000-000000000005','Vrinda Kanjivaram','vrinda-kanjivaram','An elegant drape with delicate zari-inspired detailing and a beautifully finished border. A timeless addition to your occasion wardrobe. Includes an unstitched blouse piece. Dry clean recommended.','Silk','Emerald',10990,null,9,'Kanjivaram','Wedding Edit','[{"url":"reference:4","alt":"Emerald Silk saree"}]',false,false) on conflict (slug) do nothing;
insert into public.products (id,name,slug,description,fabric,color,price,discount_price,stock,category,collection,images,is_featured,is_active) values ('00000000-0000-4000-8000-000000000006','Meher Festive Silk','meher-festive-silk','An elegant drape with delicate zari-inspired detailing and a beautifully finished border. A timeless addition to your occasion wardrobe. Includes an unstitched blouse piece. Dry clean recommended.','Silk','Wine',5990,null,10,'Banarasi','Festive Reverie','[{"url":"reference:0","alt":"Wine Silk saree"}]',false,false) on conflict (slug) do nothing;
insert into public.products (id,name,slug,description,fabric,color,price,discount_price,stock,category,collection,images,is_featured,is_active) values ('00000000-0000-4000-8000-000000000007','Chandni Tissue Drape','chandni-tissue-drape','An elegant drape with delicate zari-inspired detailing and a beautifully finished border. A timeless addition to your occasion wardrobe. Includes an unstitched blouse piece. Dry clean recommended.','Tissue silk','Champagne',5490,null,11,'Tissue','Everyday Elegance','[{"url":"reference:1","alt":"Champagne Tissue silk saree"}]',false,false) on conflict (slug) do nothing;
insert into public.products (id,name,slug,description,fabric,color,price,discount_price,stock,category,collection,images,is_featured,is_active) values ('00000000-0000-4000-8000-000000000008','Ananya Heritage Silk','ananya-heritage-silk','An elegant drape with delicate zari-inspired detailing and a beautifully finished border. A timeless addition to your occasion wardrobe. Includes an unstitched blouse piece. Dry clean recommended.','Silk','Ruby',9490,null,12,'Kanjivaram','Banarasi Heirlooms','[{"url":"reference:2","alt":"Ruby Silk saree"}]',false,false) on conflict (slug) do nothing;
