'use client';
import {useState} from 'react';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {z} from 'zod';
import {ArrowUpRight} from 'lucide-react';
const schema=z.object({customer_name:z.string().min(2,'Please enter your name.'),email:z.email('Please enter a valid email.'),phone:z.string().max(30),message:z.string().min(5,'Please add a few details.').max(4000)});
type Values=z.infer<typeof schema>;
export function EnquiryForm({productId,initialMessage='',checkoutItems,onSuccess}:{productId?:string;initialMessage?:string;checkoutItems?:{product_id:string;quantity:number}[];onSuccess?:(message:string)=>void}){const [status,setStatus]=useState('');const {register,handleSubmit,formState:{errors,isSubmitting},reset}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{message:initialMessage}});return <form className="enquiry-form" onSubmit={handleSubmit(async values=>{setStatus('');try{const r=await fetch(checkoutItems?'/api/orders':'/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,product_id:productId,items:checkoutItems})});const data=await r.json();if(!r.ok)throw Error(data.error);const message='Thank you. Our team will follow up using the contact details you provided.';setStatus(message);onSuccess?.(message);reset();}catch(e){setStatus(e instanceof Error?e.message:'Could not send. Please try again.');}})}><div className="form-row"><label>Your name<input autoComplete="name" {...register('customer_name')}/><small className="form-error">{errors.customer_name?.message}</small></label><label>Email address<input type="email" autoComplete="email" {...register('email')}/><small className="form-error">{errors.email?.message}</small></label></div><label>Phone number <small>(optional)</small><input type="tel" autoComplete="tel" {...register('phone')}/></label><label>{checkoutItems?'Delivery address & special requests':'How can we help?'}<textarea rows={4} {...register('message')}/><small className="form-error">{errors.message?.message}</small></label><small>By sending, you agree that our team may contact you about this request.</small><button disabled={isSubmitting} className="button">{isSubmitting?'SENDING…':checkoutItems?'SEND ORDER REQUEST':'SEND ENQUIRY'} <ArrowUpRight size={17}/></button>{status&&<p role="status" className="form-status">{status}</p>}</form>;}
