'use client';
import {createContext,useContext,useEffect,useState,ReactNode} from 'react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {Product} from '@/lib/catalog';
type Item={product:Product;quantity:number};
type Store={items:Item[];wishes:string[];add:(p:Product)=>void;quantity:(id:string,n:number)=>void;toggle:(id:string)=>void;clear:()=>void;notice:string;notify:(s:string)=>void};
const Context=createContext<Store>(null!);
export function Providers({children}:{children:ReactNode}){const [query]=useState(()=>new QueryClient({defaultOptions:{queries:{staleTime:60*1000,refetchOnWindowFocus:false}}}));const [items,setItems]=useState<Item[]>([]);const [wishes,setWishes]=useState<string[]>([]);const [ready,setReady]=useState(false);const [notice,notify]=useState('');useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem('krishna-bag')||'[]'));setWishes(JSON.parse(localStorage.getItem('krishna-wishlist')||'[]'));}catch{}setReady(true);},[]);useEffect(()=>{if(ready){localStorage.setItem('krishna-bag',JSON.stringify(items));localStorage.setItem('krishna-wishlist',JSON.stringify(wishes));}},[items,wishes,ready]);useEffect(()=>{if(notice){const timer=setTimeout(()=>notify(''),3500);return()=>clearTimeout(timer);}},[notice]);const add=(p:Product)=>{if(p.stock<1){notify('This piece is currently out of stock.');return;}setItems(old=>{const found=old.find(i=>i.product.id===p.id);return found?old.map(i=>i.product.id===p.id?{...i,quantity:Math.min(i.quantity+1,p.stock)}:i):[...old,{product:p,quantity:1}];});notify('A beautiful choice. Added to your bag.');void fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:p.id,event_type:'add_to_cart'})});};return <QueryClientProvider client={query}><Context.Provider value={{items,wishes,add,quantity:(id,n)=>setItems(old=>old.map(i=>i.product.id===id?{...i,quantity:Math.min(n,i.product.stock)}:i).filter(i=>i.quantity>0)),toggle:id=>setWishes(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]),clear:()=>setItems([]),notice,notify}}>{children}{notice&&<div className="toast" role="status">{notice}</div>}</Context.Provider></QueryClientProvider>;}
export const useStore=()=>useContext(Context);
