export type Product = {id:string;department?:string;name:string;slug:string;description:string;fabric:string;color:string;price:number;discount_price:number|null;stock:number;category:string;collection:string;images:{url:string;alt:string;public_id?:string}[];is_featured:boolean;is_active:boolean;view_count?:number;enquiry_count?:number};
export const brand = 'Krishna Sarees And Readymade';
export const collections = [ {name:'The Wedding Edit',slug:'wedding-edit',tag:'For your forever moments',art:0}, {name:'Banarasi Heirlooms',slug:'banarasi-heirlooms',tag:'A legacy in every weave',art:1}, {name:'Festive Reverie',slug:'festive-reverie',tag:'Made for celebration',art:2}, {name:'Everyday Elegance',slug:'everyday-elegance',tag:'Little luxuries, every day',art:3} ];
export const samples:Product[] = [
 ['Gulab Banarasi Silk','gulab-banarasi-silk','Silk','Wine',8990,'Banarasi','Wedding Edit',0],
 ['Noor Tissue Silk','noor-tissue-silk','Tissue silk','Champagne',6490,'Tissue','Banarasi Heirlooms',1],
 ['Ragini Zari Saree','ragini-zari-saree','Silk','Ruby',7290,'Banarasi','Festive Reverie',2],
 ['Sunehri Chanderi','sunehri-chanderi','Chanderi','Gold',4290,'Chanderi','Everyday Elegance',3],
 ['Vrinda Kanjivaram','vrinda-kanjivaram','Silk','Emerald',10990,'Kanjivaram','Wedding Edit',4],
 ['Meher Festive Silk','meher-festive-silk','Silk','Wine',5990,'Banarasi','Festive Reverie',0],
 ['Chandni Tissue Drape','chandni-tissue-drape','Tissue silk','Champagne',5490,'Tissue','Everyday Elegance',1],
 ['Ananya Heritage Silk','ananya-heritage-silk','Silk','Ruby',9490,'Kanjivaram','Banarasi Heirlooms',2]
 ].map((p,i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,name:String(p[0]),slug:String(p[1]),fabric:String(p[2]),color:String(p[3]),price:Number(p[4]),discount_price:null,stock:5+i,category:String(p[5]),collection:String(p[6]),images:[{url:`reference:${p[7]}`,alt:`${p[3]} ${p[2]} saree` }],description:'An elegant drape with delicate zari-inspired detailing and a beautifully finished border. A timeless addition to your occasion wardrobe. Includes an unstitched blouse piece. Dry clean recommended.',is_featured:i<4,is_active:true}));
export const defaultSettings = {logo_url:'',favicon_url:'',store_name:brand,tagline:'Woven with tradition. Worn with love.',about_text:'Some things never go out of style. The grace of a saree. The joy of dressing up. The pieces we pass down. At Krishna, we bring together beautiful sarees and readymade favourites for the everyday moments and the unforgettable ones.',contact_email:'',contact_phone:'',address:'',opening_time:'',closing_time:'',working_days:[] as string[],social_links:{} as Record<string,string>,policy_documents:[] as {url:string;name:string}[],shipping_policy:'Please contact our team to confirm shipping availability, charges and delivery times for your address.',returns_policy:'Please confirm return and exchange eligibility with our team before placing your order.'};
export type Settings = typeof defaultSettings;
export const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
export const articles=[{slug:'a-guide-to-your-first-banarasi',title:'Your first Banarasi: a love story in silk',category:'The fabric journal',body:'A Banarasi saree brings together intricate motifs, rich colour and a distinctive drape. Start with the occasion: deeper jewel tones lend themselves to evening celebrations, while softer shades feel effortless in daylight. Ask about the fibre composition and weave before buying. Pair a statement border with simple jewellery to let the fabric take centre stage.'},{slug:'caring-for-your-silk',title:'A little care. A lifetime of beauty.',category:'Care & keeping',body:'Always follow the care label supplied with your saree. For delicate silk and zari, professional dry cleaning is generally the gentlest choice. Air your saree after wear, keep it away from direct sunlight and store it loosely in breathable cotton. Refold periodically along different lines and avoid spraying perfume directly on the fabric.'},{slug:'the-art-of-occasion-dressing',title:'A saree for every kind of celebration',category:'Style notes',body:'There is no single way to dress for a celebration. Choose a fabric that feels comfortable, a colour you love and details that reflect your mood. A light tissue drape can feel festive without weight; a rich silk makes a beautiful evening statement. Our team can help you compare options for your budget and occasion.'}];
